version: '2.0.{build}.0'

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  parallel: true
  project: 'BuildTasks.TextTemplating.sln'
  publish_nuget: true

after_build:
  - cmd: nuget pack BuildTasks.TextTemplating.nuspec -version "%APPVEYOR_BUILD_VERSION%"

artifacts:
  path: 'BuildTasks.TextTemplating*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: srBMVDnPbP0bAvQALTu0Pi+wQWUWCSDExxmbN5HQ/kDXQvvzf/hPwdV5e4zBnhVG
  artifact: /BuildTasks.TextTemplating.*\.nupkg/
  skip_symbols: false
